/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Sharon Zuleta
 */
public class GestionUsuariosAdmin extends javax.swing.JPanel {

    /**
     * Creates new form GestionUsuariosAdmin
     */
    public GestionUsuariosAdmin() {
        initComponents();
        
            this.setSize(500, 469);
            this.setBackground(Color.white);
    }
    
    public JButton getbtnCerrarGestion(){       
        return btnCerrarGestion;        
    }
    
    public void setbtnCerrarGestion(JButton btnCerrarGestion){
        this.btnCerrarGestion = btnCerrarGestion;        
    }
    
    public JButton getbtnRegistroUsuario(){       
        return btnRegistroUsuario;        
    }
    
    public void setbtnbtnRegistroUsuario(JButton btnRegistroUsuario){
        this.btnRegistroUsuario = btnRegistroUsuario;        
    }
    
    public JButton getbtnModificarUsuario(){       
        return btnModificarUsuario;        
    }
    
    public void setbtnModificarUsuario(JButton btnModificarUsuario){
        this.btnModificarUsuario = btnModificarUsuario;        
    }
    
    public JButton getbtnConsultarUsuario(){       
        return btnConsultarUsuario;        
    }
    
    public void setbtnConsultarUsuario(JButton btnConsultarUsuario){
        this.btnConsultarUsuario = btnConsultarUsuario;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarGestion = new javax.swing.JButton();
        jlGestionUsuarios = new javax.swing.JLabel();
        btnRegistroUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnConsultarUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        btnCerrarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-xbox-x-48.png"))); // NOI18N
        btnCerrarGestion.setBorderPainted(false);
        btnCerrarGestion.setContentAreaFilled(false);

        jlGestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jlGestionUsuarios.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 48)); // NOI18N
        jlGestionUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        jlGestionUsuarios.setText("Gestionar usuarios");

        btnRegistroUsuario.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnRegistroUsuario.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistroUsuario.setText("Registrar nuevo usuario");
        btnRegistroUsuario.setBorderPainted(false);
        btnRegistroUsuario.setContentAreaFilled(false);

        btnModificarUsuario.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnModificarUsuario.setForeground(new java.awt.Color(102, 102, 102));
        btnModificarUsuario.setText("Modificar usuario");
        btnModificarUsuario.setBorderPainted(false);
        btnModificarUsuario.setContentAreaFilled(false);

        btnConsultarUsuario.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnConsultarUsuario.setForeground(new java.awt.Color(102, 102, 102));
        btnConsultarUsuario.setText("Consultar usuario");
        btnConsultarUsuario.setBorderPainted(false);
        btnConsultarUsuario.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnRegistroUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarUsuario)
                            .addComponent(btnModificarUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlGestionUsuarios)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlGestionUsuarios)
                .addGap(53, 53, 53)
                .addComponent(btnRegistroUsuario)
                .addGap(35, 35, 35)
                .addComponent(btnModificarUsuario)
                .addGap(41, 41, 41)
                .addComponent(btnConsultarUsuario)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarGestion;
    private javax.swing.JButton btnConsultarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnRegistroUsuario;
    private javax.swing.JLabel jlGestionUsuarios;
    // End of variables declaration//GEN-END:variables
}
