/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Sharon Zuleta
 */
public class GestionClientesOp extends javax.swing.JPanel {

    /**
     * Creates new form GestionClientesOp
     */
    public GestionClientesOp() {
        initComponents();
        
            this.setSize(458, 469);
            this.setBackground(Color.white);
    }
    
    public JButton getbtnRegistroCliente(){       
        return btnRegistroCliente;        
    }
    
    public void setbtnRegistroCliente(JButton btnRegistroCliente){
        this.btnRegistroCliente = btnRegistroCliente;        
    }
    
    public JButton getbtnModificarCliente(){       
        return btnModificarCliente;        
    }
    
    public void setbtnModificarCliente(JButton btnModificarCliente){
        this.btnModificarCliente = btnModificarCliente;        
    }
    
    public JButton getbtnConsultarCliente(){       
        return btnConsultarCliente;        
    }
    
    public void setbtnConsultarCliente(JButton btnConsultarCliente){
        this.btnConsultarCliente = btnConsultarCliente;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlGestionClientes = new javax.swing.JLabel();
        btnRegistroCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jlGestionClientes.setBackground(new java.awt.Color(255, 255, 255));
        jlGestionClientes.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 48)); // NOI18N
        jlGestionClientes.setForeground(new java.awt.Color(102, 102, 102));
        jlGestionClientes.setText("Gestionar Clientes");

        btnRegistroCliente.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnRegistroCliente.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistroCliente.setText("Registrar nuevo cliente");
        btnRegistroCliente.setBorderPainted(false);
        btnRegistroCliente.setContentAreaFilled(false);

        btnModificarCliente.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnModificarCliente.setForeground(new java.awt.Color(102, 102, 102));
        btnModificarCliente.setText("Modificar cliente");
        btnModificarCliente.setBorderPainted(false);
        btnModificarCliente.setContentAreaFilled(false);

        btnConsultarCliente.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnConsultarCliente.setForeground(new java.awt.Color(102, 102, 102));
        btnConsultarCliente.setText("Consultar cliente");
        btnConsultarCliente.setBorderPainted(false);
        btnConsultarCliente.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnRegistroCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarCliente)
                            .addComponent(btnModificarCliente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGestionClientes)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlGestionClientes)
                .addGap(53, 53, 53)
                .addComponent(btnRegistroCliente)
                .addGap(35, 35, 35)
                .addComponent(btnModificarCliente)
                .addGap(41, 41, 41)
                .addComponent(btnConsultarCliente)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnRegistroCliente;
    private javax.swing.JLabel jlGestionClientes;
    // End of variables declaration//GEN-END:variables
}
