/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Sharon Zuleta
 */
public class GestionActivos extends javax.swing.JPanel {

    /**
     * Creates new form GestionActivos
     */
    public GestionActivos() {
        initComponents();
        
            this.setSize(400, 443);
            this.setBackground(Color.white);
    }
    
    public JButton getbtnRegistroActivos(){       
        return btnRegistroActivos;        
    }
    
    public void setbtnbtnRegistroActivos(JButton btnRegistroActivos){
        this.btnRegistroActivos = btnRegistroActivos;        
    }
    
    public JButton getbtnModificarActivos(){       
        return btnModificarActivos;        
    }
    
    public void setbtnModificarActivos(JButton btnModificarActivos){
        this.btnModificarActivos = btnModificarActivos;        
    }
    
    public JButton getbtnConsultarActivos(){       
        return btnConsultarActivos;        
    }
    
    public void setbtnConsultarActivos(JButton btnConsultarActivos){
        this.btnConsultarActivos = btnConsultarActivos;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlGestionActivos = new javax.swing.JLabel();
        btnRegistroActivos = new javax.swing.JButton();
        btnModificarActivos = new javax.swing.JButton();
        btnConsultarActivos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jlGestionActivos.setBackground(new java.awt.Color(255, 255, 255));
        jlGestionActivos.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 48)); // NOI18N
        jlGestionActivos.setForeground(new java.awt.Color(102, 102, 102));
        jlGestionActivos.setText("Gestionar activos");

        btnRegistroActivos.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnRegistroActivos.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistroActivos.setText("Registrar nuevo activo");
        btnRegistroActivos.setBorderPainted(false);
        btnRegistroActivos.setContentAreaFilled(false);

        btnModificarActivos.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnModificarActivos.setForeground(new java.awt.Color(102, 102, 102));
        btnModificarActivos.setText("Modificar activo");
        btnModificarActivos.setBorderPainted(false);
        btnModificarActivos.setContentAreaFilled(false);
        btnModificarActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActivosActionPerformed(evt);
            }
        });

        btnConsultarActivos.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnConsultarActivos.setForeground(new java.awt.Color(102, 102, 102));
        btnConsultarActivos.setText("Consultar activo");
        btnConsultarActivos.setBorderPainted(false);
        btnConsultarActivos.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlGestionActivos)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistroActivos)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultarActivos)
                    .addComponent(btnModificarActivos))
                .addGap(85, 119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlGestionActivos)
                .addGap(53, 53, 53)
                .addComponent(btnRegistroActivos)
                .addGap(36, 36, 36)
                .addComponent(btnModificarActivos)
                .addGap(41, 41, 41)
                .addComponent(btnConsultarActivos)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarActivos;
    private javax.swing.JButton btnModificarActivos;
    private javax.swing.JButton btnRegistroActivos;
    private javax.swing.JLabel jlGestionActivos;
    // End of variables declaration//GEN-END:variables
}
