/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Sharon Zuleta
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

            this.setSize(457, 643);
            this.setBackground(Color.white);
    }
    
    public JButton getbtnIngresoLogin(){       
        return btnIngresoLogin;        
    }
    
    public void setbtnIngresoLogin(JButton btnIngresoLogin){
        this.btnIngresoLogin = btnIngresoLogin;        
    }
    
    public JTextField getjtIngresoContrasenia(){
        return jtIngresoContrasenia;
    }
    
    public void setjtIngresoContrasenia(JTextField jtIngresoContrasenia){
        this.jtIngresoContrasenia = jtIngresoContrasenia;
    }
    
    public JTextField getjtIngresoUser(){
        return jtIngresoUser;
    }
    
    public void setjtIngresoUser(JTextField jtIngresoUser){
        this.jtIngresoUser = jtIngresoUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackgroundLogin = new javax.swing.JPanel();
        jpBackgroundLogin1 = new javax.swing.JPanel();
        jtIngresoUser = new javax.swing.JTextField();
        jtIngresoContrasenia = new javax.swing.JTextField();
        jlUsuario = new javax.swing.JLabel();
        jlContrasenia = new javax.swing.JLabel();
        jlIconUser = new javax.swing.JLabel();
        btnIngresoLogin = new javax.swing.JButton();
        jlIniciarSesion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        setMaximumSize(new java.awt.Dimension(437, 621));

        jpBackgroundLogin.setBackground(new java.awt.Color(102, 102, 102));

        jpBackgroundLogin1.setBackground(new java.awt.Color(255, 255, 255));

        jlUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jlUsuario.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlUsuario.setText("Usuario:");

        jlContrasenia.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        jlContrasenia.setForeground(new java.awt.Color(102, 102, 102));
        jlContrasenia.setText("Contraseña:");

        jlIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-user-96.png"))); // NOI18N

        btnIngresoLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresoLogin.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        btnIngresoLogin.setForeground(new java.awt.Color(102, 102, 102));
        btnIngresoLogin.setText("Ingresar");
        btnIngresoLogin.setBorderPainted(false);

        javax.swing.GroupLayout jpBackgroundLogin1Layout = new javax.swing.GroupLayout(jpBackgroundLogin1);
        jpBackgroundLogin1.setLayout(jpBackgroundLogin1Layout);
        jpBackgroundLogin1Layout.setHorizontalGroup(
            jpBackgroundLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundLogin1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlIconUser)
                .addGap(146, 146, 146))
            .addGroup(jpBackgroundLogin1Layout.createSequentialGroup()
                .addGroup(jpBackgroundLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBackgroundLogin1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jpBackgroundLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlContrasenia)
                            .addComponent(jlUsuario)
                            .addComponent(jtIngresoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtIngresoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpBackgroundLogin1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnIngresoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpBackgroundLogin1Layout.setVerticalGroup(
            jpBackgroundLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundLogin1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlIconUser)
                .addGap(29, 29, 29)
                .addComponent(jlUsuario)
                .addGap(18, 18, 18)
                .addComponent(jtIngresoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jlContrasenia)
                .addGap(18, 18, 18)
                .addComponent(jtIngresoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnIngresoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jlIniciarSesion.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jlIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jlIniciarSesion.setText("Iniciar sesión ");

        javax.swing.GroupLayout jpBackgroundLoginLayout = new javax.swing.GroupLayout(jpBackgroundLogin);
        jpBackgroundLogin.setLayout(jpBackgroundLoginLayout);
        jpBackgroundLoginLayout.setHorizontalGroup(
            jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlIniciarSesion)
                .addGap(127, 127, 127))
            .addGroup(jpBackgroundLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jpBackgroundLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpBackgroundLoginLayout.setVerticalGroup(
            jpBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(jpBackgroundLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroundLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroundLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoLogin;
    private javax.swing.JLabel jlContrasenia;
    private javax.swing.JLabel jlIconUser;
    private javax.swing.JLabel jlIniciarSesion;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpBackgroundLogin;
    private javax.swing.JPanel jpBackgroundLogin1;
    private javax.swing.JTextField jtIngresoContrasenia;
    private javax.swing.JTextField jtIngresoUser;
    // End of variables declaration//GEN-END:variables
}
