/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Sharon Zuleta
 */
public class ModificacionExitosa extends javax.swing.JPanel {

    /**
     * Creates new form ModificacionExitosa
     */
    public ModificacionExitosa() {
        initComponents();
        
            this.setSize(550, 300);
            this.setBackground(Color.white);
        
    }
    
    public JButton getbtnAceptarModi(){       
        return btnAceptarModi;        
    }
    
    public void setbtnAceptarModi(JButton btnAceptarModi){
        this.btnAceptarModi = btnAceptarModi;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTexto = new javax.swing.JLabel();
        btnAceptarModi = new javax.swing.JButton();
        jpBack = new javax.swing.JPanel();
        jlTituloModificar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jlTexto.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlTexto.setForeground(new java.awt.Color(102, 102, 102));
        jlTexto.setText("El usuario se ha modificado de manera exitosa.");

        btnAceptarModi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOK.png"))); // NOI18N
        btnAceptarModi.setBorderPainted(false);
        btnAceptarModi.setContentAreaFilled(false);
        btnAceptarModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarModiActionPerformed(evt);
            }
        });

        jpBack.setBackground(new java.awt.Color(102, 102, 102));

        jlTituloModificar.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jlTituloModificar.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloModificar.setText("MODIFICAR USUARIO");

        javax.swing.GroupLayout jpBackLayout = new javax.swing.GroupLayout(jpBack);
        jpBack.setLayout(jpBackLayout);
        jpBackLayout.setHorizontalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTituloModificar)
                .addGap(132, 132, 132))
        );
        jpBackLayout.setVerticalGroup(
            jpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jlTituloModificar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jlTexto)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarModi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jlTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnAceptarModi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarModiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarModi;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JLabel jlTituloModificar;
    private javax.swing.JPanel jpBack;
    // End of variables declaration//GEN-END:variables
}
