/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Sharon Zuleta
 */
public class ModificarActivos extends javax.swing.JPanel {

    /**
     * Creates new form ModificarActivos
     */
    public ModificarActivos() {
        initComponents();
        
            this.setSize(1360, 740);
            this.setBackground(Color.white);
    }
    
    public JTextField getjtID (){
        return jtID;
    }
    
    public void setjtID (JTextField jtID){
        this.jtID = jtID;
    }
    
    public JTextField getjtMarca (){
        return jtMarca;
    }
    
    public void setjtMarca (JTextField jtMarca){
        this.jtMarca = jtMarca;
    }
    
    public JComboBox getcbFases (){
        return cbFases;
    }
    
    public void setcbFases (JComboBox cbFases){
        this.cbFases = cbFases;
    }
    
    public JTextField getjtSnom (){
        return jtSnom;
    }
    
    public void setjtSnom (JTextField jtSnom){
        this.jtSnom = jtSnom;
    }
    
    public JComboBox getcbActividad (){
        return cbActividad;
    }
    
    public void setcbActividad (JComboBox cbActividad){
        this.cbActividad = cbActividad;
    }
        
    public JTextField getjtV1nom (){
        return jtV1nom;
    }
    
    public void setjtV1nom (JTextField jtV1nom){
        this.jtV1nom = jtV1nom;
    }
    
    public JTextField getjtV2nom (){
        return jtV2nom;
    }
    
    public void setjtV2nom (JTextField jtV2nom){
        this.jtV2nom = jtV2nom;
    }
    
    public JTextField getjtFrecuencia (){
        return jtFrecuencia;
    }
    
    public void setjtFrecuencia (JTextField jtFrecuencia){
        this.jtFrecuencia = jtFrecuencia;
    }
      
    public JButton getbtnDevolver (){
        return btnDevolver;
    }
    
    public void setbtnDevolver (JButton btnDevolver){
        this.btnDevolver = btnDevolver;
    }
    
    public JButton getbtnModificarActivo (){
        return btnModificarActivo;
    }
    
    public void setbtnModificarActivo (JButton btnModificarActivo){
        this.btnModificarActivo = btnModificarActivo;
    }
    
     public JTextField getjtGeoreferenciacion (){
        return jtGeoreferenciacion;
    }
    
    public void setjtGeoreferenciacion (JTextField jtGeoreferenciacion){
        this.jtGeoreferenciacion = jtGeoreferenciacion;
    }
    
    public JTextField getjtBarrio (){
        return jtBarrio;
    }
    
    public void setjtBarrio (JTextField jtBarrio){
        this.jtBarrio = jtBarrio;
    }
    
    public JTextField getjtComuna (){
        return jtComuna;
    }
    
    public void setjtComuna (JTextField jtComuna){
        this.jtComuna = jtComuna;
    }

    public JLabel getLabelMensaje() {
        return jLabelMensaje;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificarActivo = new javax.swing.JButton();
        jpTituloAdmin = new javax.swing.JPanel();
        jlAdministrador = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtGeoreferenciacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtBarrio = new javax.swing.JTextField();
        jtComuna = new javax.swing.JTextField();
        jlFrecuencia = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtFrecuencia = new javax.swing.JTextField();
        jtV2nom = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlFases = new javax.swing.JLabel();
        jtV1nom = new javax.swing.JTextField();
        jlRol = new javax.swing.JLabel();
        jlActividad = new javax.swing.JLabel();
        cbActividad = new javax.swing.JComboBox<>();
        jlV1nom = new javax.swing.JLabel();
        jlV2nom = new javax.swing.JLabel();
        jtSnom = new javax.swing.JTextField();
        cbFases = new javax.swing.JComboBox<>();
        jLabelMensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        btnModificarActivo.setBackground(new java.awt.Color(204, 204, 204));
        btnModificarActivo.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnModificarActivo.setForeground(new java.awt.Color(102, 102, 102));
        btnModificarActivo.setText("Modificar activo");
        btnModificarActivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btnModificarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActivoActionPerformed(evt);
            }
        });

        jpTituloAdmin.setBackground(new java.awt.Color(102, 102, 102));
        jpTituloAdmin.setPreferredSize(new java.awt.Dimension(1352, 120));

        jlAdministrador.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jlAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        jlAdministrador.setText("Administrador");

        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconDevolver.png"))); // NOI18N
        btnDevolver.setBorderPainted(false);
        btnDevolver.setContentAreaFilled(false);

        javax.swing.GroupLayout jpTituloAdminLayout = new javax.swing.GroupLayout(jpTituloAdmin);
        jpTituloAdmin.setLayout(jpTituloAdminLayout);
        jpTituloAdminLayout.setHorizontalGroup(
            jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloAdminLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpTituloAdminLayout.setVerticalGroup(
            jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloAdminLayout.createSequentialGroup()
                .addGroup(jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTituloAdminLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlAdministrador))
                    .addGroup(jpTituloAdminLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnDevolver)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Modificar activo");

        jLabel2.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Georeferenciación:");

        jLabel3.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Barrio:");

        jLabel4.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Comuna:");

        jtComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComunaActionPerformed(evt);
            }
        });

        jlFrecuencia.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlFrecuencia.setForeground(new java.awt.Color(102, 102, 102));
        jlFrecuencia.setText("Frecuencia:");

        jlID.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlID.setForeground(new java.awt.Color(102, 102, 102));
        jlID.setText("Id:");

        jlMarca.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlMarca.setForeground(new java.awt.Color(102, 102, 102));
        jlMarca.setText("Marca:");

        jlFases.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlFases.setForeground(new java.awt.Color(102, 102, 102));
        jlFases.setText("Fases:");

        jlRol.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlRol.setForeground(new java.awt.Color(102, 102, 102));
        jlRol.setText("Snom (KVA):");

        jlActividad.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlActividad.setForeground(new java.awt.Color(102, 102, 102));
        jlActividad.setText("Actividad:");

        cbActividad.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        cbActividad.setForeground(new java.awt.Color(102, 102, 102));
        cbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la actividad...", "Verdadero\t", "Falso" }));

        jlV1nom.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlV1nom.setForeground(new java.awt.Color(102, 102, 102));
        jlV1nom.setText("v1nom (V):");

        jlV2nom.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlV2nom.setForeground(new java.awt.Color(102, 102, 102));
        jlV2nom.setText("v2nom (V):");

        cbFases.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        cbFases.setForeground(new java.awt.Color(102, 102, 102));
        cbFases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una fase...", "Monofásico", "Bifásico", "Trifásico", " " }));

        jLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText(" ");
        jLabelMensaje.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 1481, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID)
                            .addComponent(jlMarca)
                            .addComponent(jlFases)
                            .addComponent(jlRol))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtSnom)
                            .addComponent(jtID)
                            .addComponent(cbFases, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtGeoreferenciacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlV2nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtV2nom, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlV1nom)
                            .addComponent(jlActividad))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtV1nom, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFrecuencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(532, 532, 532))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(445, 445, 445))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID)
                    .addComponent(jlActividad)
                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMarca)
                    .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlV1nom)
                    .addComponent(jtV1nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFases)
                    .addComponent(cbFases, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlV2nom)
                    .addComponent(jtV2nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRol)
                    .addComponent(jtSnom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFrecuencia)
                    .addComponent(jtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtGeoreferenciacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActivoActionPerformed

    private void jtComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtComunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnModificarActivo;
    private javax.swing.JComboBox<String> cbActividad;
    private javax.swing.JComboBox<String> cbFases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jlActividad;
    private javax.swing.JLabel jlAdministrador;
    private javax.swing.JLabel jlFases;
    private javax.swing.JLabel jlFrecuencia;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlRol;
    private javax.swing.JLabel jlV1nom;
    private javax.swing.JLabel jlV2nom;
    private javax.swing.JPanel jpTituloAdmin;
    private javax.swing.JTextField jtBarrio;
    private javax.swing.JTextField jtComuna;
    private javax.swing.JTextField jtFrecuencia;
    private javax.swing.JTextField jtGeoreferenciacion;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtSnom;
    private javax.swing.JTextField jtV1nom;
    private javax.swing.JTextField jtV2nom;
    // End of variables declaration//GEN-END:variables
}
