/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Sharon Zuleta
 */
public class Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Pagos
     */
    public Pagos() {
        initComponents();
    }
    
    public JTextField getjtIdFactura (){
        return jtIdFactura;
    }
    
    public void setjtCedula (JTextField jtIdFactura){
        this.jtIdFactura = jtIdFactura;
    }
    
    public JComboBox getcbMetodoPago (){
        return cbMetodoPago;
    }
    
    public void setcbMetodoPago (JComboBox cbMetodoPago){
        this.cbMetodoPago = cbMetodoPago;
    }

    public JButton getbtnPagar (){
        return btnPagar;
    }
    
    public void setbtnPagar (JButton btnPagar){
        this.btnPagar = btnPagar;
    }
    
    public JButton getbtnDevolver (){
        return btnDevolver;
    }
    
    public void setbtnDevolver (JButton btnDevolver){
        this.btnDevolver = btnDevolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackgroundTitulo = new javax.swing.JPanel();
        jlTituloGerente = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtIdFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMetodoPago = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInformacionPago = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jpBackgroundTitulo.setBackground(new java.awt.Color(102, 102, 102));

        jlTituloGerente.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jlTituloGerente.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloGerente.setText("Operador");

        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconDevolver.png"))); // NOI18N
        btnDevolver.setBorderPainted(false);
        btnDevolver.setContentAreaFilled(false);

        javax.swing.GroupLayout jpBackgroundTituloLayout = new javax.swing.GroupLayout(jpBackgroundTitulo);
        jpBackgroundTitulo.setLayout(jpBackgroundTituloLayout);
        jpBackgroundTituloLayout.setHorizontalGroup(
            jpBackgroundTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackgroundTituloLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlTituloGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1103, Short.MAX_VALUE)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpBackgroundTituloLayout.setVerticalGroup(
            jpBackgroundTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBackgroundTituloLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jlTituloGerente)
                .addGap(36, 36, 36))
            .addGroup(jpBackgroundTituloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnDevolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Registro de pagos");

        jLabel2.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Id factura:");

        jLabel3.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Método de pago:");

        cbMetodoPago.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        cbMetodoPago.setForeground(new java.awt.Color(102, 102, 102));
        cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el método de pago...", "Directo", "Banco 1", "Banco 2", " " }));

        btnPagar.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(102, 102, 102));
        btnPagar.setText("PAGAR");

        TablaInformacionPago.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 14)); // NOI18N
        TablaInformacionPago.setForeground(new java.awt.Color(102, 102, 102));
        TablaInformacionPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Pago", "Id Factura", "Método de pago", "Fecha de realización"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaInformacionPago);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroundTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBackgroundTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtIdFactura)
                        .addComponent(jLabel3)
                        .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(btnPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInformacionPago;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTituloGerente;
    private javax.swing.JPanel jpBackgroundTitulo;
    private javax.swing.JTextField jtIdFactura;
    // End of variables declaration//GEN-END:variables
}
