/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Sharon Zuleta
 */
public class RegistroUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form RegistroUsuarios
     */
    public RegistroUsuarios() {
        initComponents();

        this.setSize(1360, 740);
        this.setBackground(Color.white);
    }

    public JTextField getjtNombre() {
        return jtNombre;
    }

    public void setjtNombre(JTextField jtNombre) {
        this.jtNombre = jtNombre;
    }

    public JTextField getjtCedula() {
        return jtCedula;
    }

    public void setjtCedula(JTextField jtCedula) {
        this.jtCedula = jtCedula;
    }

    public JTextField getjtApellido() {
        return jtApellido;
    }

    public void setjtApellido(JTextField jtApellido) {
        this.jtApellido = jtApellido;
    }

    public JTextField getjtCelular() {
        return jtCelular;
    }

    public void setjtCelular(JTextField jtCelular) {
        this.jtCelular = jtCelular;
    }

    public JTextField getjtEmail() {
        return jtEmail;
    }

    public void setjtEmail(JTextField jtEmail) {
        this.jtEmail = jtEmail;
    }

    public JPasswordField getjtContrasenia() {
        return jtContrasenia;
    }

    public void setjtContrasenia(JPasswordField jtContrasenia) {
        this.jtContrasenia = jtContrasenia;
    }

    public JComboBox getcbRol() {
        return cbRol;
    }

    public void setcbRol(JComboBox cbRol) {
        this.cbRol = cbRol;
    }

    public JComboBox getcbActividad() {
        return cbActividad;
    }

    public void setcbActividad(JComboBox cbActividad) {
        this.cbActividad = cbActividad;
    }

    public JButton getbtnDevolver() {
        return btnDevolver;
    }

    public void setbtnDevolver(JButton btnDevolver) {
        this.btnDevolver = btnDevolver;
    }

    public JButton getbtnRegistrar() {
        return btnRegistrar;
    }

    public void setbtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JLabel getLabelMensaje() {
        return jLabelMensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpTituloAdmin = new javax.swing.JPanel();
        jlAdministrador = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlCedula = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlRol = new javax.swing.JLabel();
        jlActividad = new javax.swing.JLabel();
        jlCelular = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlContrasenia = new javax.swing.JLabel();
        jtCedula = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCelular = new javax.swing.JTextField();
        cbRol = new javax.swing.JComboBox<>();
        cbActividad = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jtContrasenia = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jpTituloAdmin.setBackground(new java.awt.Color(102, 102, 102));
        jpTituloAdmin.setPreferredSize(new java.awt.Dimension(1352, 120));

        jlAdministrador.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 36)); // NOI18N
        jlAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        jlAdministrador.setText("Administrador");

        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconDevolver.png"))); // NOI18N
        btnDevolver.setBorderPainted(false);
        btnDevolver.setContentAreaFilled(false);

        javax.swing.GroupLayout jpTituloAdminLayout = new javax.swing.GroupLayout(jpTituloAdmin);
        jpTituloAdmin.setLayout(jpTituloAdminLayout);
        jpTituloAdminLayout.setHorizontalGroup(
            jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloAdminLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpTituloAdminLayout.setVerticalGroup(
            jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloAdminLayout.createSequentialGroup()
                .addGroup(jpTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTituloAdminLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlAdministrador))
                    .addGroup(jpTituloAdminLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnDevolver)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Registrar nuevo usuario");

        jlCedula.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlCedula.setForeground(new java.awt.Color(102, 102, 102));
        jlCedula.setText("Cédula:");

        jlNombre.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(102, 102, 102));
        jlNombre.setText("Nombre:");

        jlApellido.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(102, 102, 102));
        jlApellido.setText("Apellido:");

        jlRol.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlRol.setForeground(new java.awt.Color(102, 102, 102));
        jlRol.setText("Rol:");

        jlActividad.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlActividad.setForeground(new java.awt.Color(102, 102, 102));
        jlActividad.setText("Actividad:");

        jlCelular.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlCelular.setForeground(new java.awt.Color(102, 102, 102));
        jlCelular.setText("Celular:");

        jlEmail.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(102, 102, 102));
        jlEmail.setText("Email:");

        jlContrasenia.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        jlContrasenia.setForeground(new java.awt.Color(102, 102, 102));
        jlContrasenia.setText("Contraseña:");

        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        cbRol.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        cbRol.setForeground(new java.awt.Color(102, 102, 102));
        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol...", "Administrador", "Gerente", "Operador", " " }));

        cbActividad.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 18)); // NOI18N
        cbActividad.setForeground(new java.awt.Color(102, 102, 102));
        cbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la actividad...", "Activo", "Inactivo" }));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrar.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(102, 102, 102));
        btnRegistrar.setText("Registrar usuario");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText(" ");
        jLabelMensaje.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTituloAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 1411, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCedula)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlRol))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(cbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlActividad)
                                .addGap(57, 57, 57)
                                .addComponent(cbActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCelular)
                                .addGap(76, 76, 76)
                                .addComponent(jtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEmail)
                                    .addComponent(jlContrasenia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(jtContrasenia)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(382, 382, 382))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(366, 366, 366)))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTituloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedula)
                    .addComponent(jlActividad)
                    .addComponent(jtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jlCelular)
                    .addComponent(jtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jlEmail)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRol)
                    .addComponent(jlContrasenia)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtApellidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbActividad;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jlActividad;
    private javax.swing.JLabel jlAdministrador;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCedula;
    private javax.swing.JLabel jlCelular;
    private javax.swing.JLabel jlContrasenia;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlRol;
    private javax.swing.JPanel jpTituloAdmin;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCedula;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JPasswordField jtContrasenia;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}